# -*- coding: utf-8 -*-
"""Copy of cse422_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16L0IvOYM7rjMCzDFu5DJEwPY5YsM-dMK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (confusion_matrix, classification_report, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve)

from collections import Counter
from imblearn.combine import SMOTEENN

from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.losses import SparseCategoricalCrossentropy

#for nn
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')
dataset=pd.read_csv("/content/drive/MyDrive/flat_price_dataset.csv")
dataset

"""# **Dataset Description**"""

print ('Shape of the dataset is {}. This dataset contains {} datapoints and {} features(including target).'.format(dataset.shape,dataset.shape[0],dataset.shape[1]))

"""# **Feature Names and its Datatypes**"""

dataset.info()

"""# Data Spliting
Select and separately store Numerical and Categorical features in different variables.
"""

##Selecting quantitative features
quantitative_data = dataset.select_dtypes(include='number')

#append the features of quantitative_data to list
quantitative_features=quantitative_data.columns.tolist()

print(f'There are {len(quantitative_features)} quantitative features:', '\n')
print(quantitative_features)
#Selecting categoricalfeatures
categorical_data=dataset.select_dtypes(include= 'object')

#append the features of categorical_data to list
categorical_features=categorical_data.columns.tolist()

print(f'There are {len(categorical_features)} categorical features:', '\n')
print(categorical_features)
# quantitative_data

"""# **Exploratory data analysis:**
In descriptive Analysis we analysis each variable separately to get inference about the feature.
# **Summary statistics of Numerical Features**
"""

quantitative_data.describe().T

"""# **Summary statistics of Categorical features**"""

categorical_data.describe().T

"""Varience"""

quantitative_data.var()

"""# **Histogram**
To find the distributions and outlier in the each numerical feature


"""

quantitative_data.hist(figsize=(12,12),bins=20)
plt.show()

"""# **Barplot of unique value counts in every categorical features**"""

for col in categorical_features:
    plt.title(f'Distribution of {col}')
    categorical_data[col].value_counts().sort_index().plot(kind='bar', rot=0, xlabel=col,ylabel='count')
    plt.show()

"""# Unique Values for both quantitative_data and catagorical_data"""

quantitative_data.nunique()

categorical_data.nunique()

"""# **Correlation Analysis**

Correlation matrix of quantitative_data
"""

# Calculate the correlation matrix
correlation_matrix = quantitative_data.corr()
# Plotting the heatmap for correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.show()

"""# **Check imbalance in the data**

We have classification problem so we need to check the balance of the given data.
"""

#If one class dominates (e.g., mostly "Medium"), KNN may mostly predict that one.
class_counts = dataset['Price_Category'].value_counts() #mostly balanced
class_counts

# Plotting
plt.figure(figsize=(8, 5))
class_counts.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Class Distribution in Price_Category')
plt.xlabel('Price_Category')
plt.ylabel('Number of Instances')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""# **Data Preprocessing**

Handling Missing Values

# Imputation
"""

quantitative_data.skew() #all are close to symmetric

from sklearn.impute import SimpleImputer

#for quantitative_data (Numerical data)
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
for col in quantitative_data:
  impute.fit(dataset[[col]])
  dataset[col] = np.round(impute.transform(dataset[[col]]), 1)


# Impute missing values in categorical data using the most frequent value
categorical_imputer = SimpleImputer(strategy='most_frequent')
for col in categorical_features:
    dataset[[col]] = categorical_imputer.fit_transform(dataset[[col]])

dataset.isnull().sum()

"""# **Encoding**
Feature Engineering

# Label encoding
"""

lable_encoding_features = ['Location', 'Has_Balcony', 'Parking_Available', 'Nearby_Schools', 'Security_Level', 'Price_Category']
mapping = {
    'Has_Balcony':{'No':0,'Yes':1},
    'Location' : {'Countryside':0,'City Center':2, 'Suburbs':1},
    'Parking_Available':{'No':0,'Yes':1},
    'Security_Level': {'Low':0, 'Medium': 1, 'High': 2},
    'Price_Category': {'Low':0, 'Medium': 1, 'High': 2},
    'Nearby_Schools':{'Few':0,'Many':1}
}
for col, map in mapping.items():
    dataset[col] = dataset[col].map(map)

"""# One-hot encoding

# **Feature Selection**
"""

# Features and target
y = dataset['Price_Category']
X = dataset.drop(columns=['Price_Category'])

"""# **Scaling**

# Standard(Usually used for data with different scale)
"""

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=0, stratify=y
)

X_train_nons, X_test_nons, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0, stratify=y
)

#train
knn.fit(X_train_nons, y_train)
# scoring on the scaled test set
print("Without sacling accuracy: {:.2f}".format(
    knn.score(X_test_nons, y_test)))

#train
knn.fit(X_train, y_train)

# scoring on the scaled test set
print("Scaled test set accuracy: {:.2f}".format(
    knn.score(X_test, y_test)))

"""# Minmax"""

from sklearn.preprocessing import MinMaxScaler
# preprocessing using 0-1 scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
# 2. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=0, stratify=y
)

X_train_nons, X_test_nons, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0, stratify=y
)

#train
knn.fit(X_train_nons, y_train)
# scoring on the scaled test set
print("Without sacling accuracy: {:.2f}".format(
    knn.score(X_test_nons, y_test)))


#train
knn.fit(X_train, y_train)

# scoring on the scaled test set
print("Scaled test set accuracy: {:.2f}".format(
    knn.score(X_test, y_test)))

#to check if range{0 to 1}
# print("per-feature minimum before scaling:\n {}".format(X_train_nons.min(axis=0)))
# print("per-feature maximum before scaling:\n {}".format(X_train_nons.max(axis=0)))
# print("per-feature minimum after scaling:\n {}".format(
#     X_train.min(axis=0)))
# print("per-feature maximum after scaling:\n {}".format(
#     X_train.max(axis=0)))

"""# **Confusion Matrix**
**Correlation:**
"""

# Calculate the correlation matrix
correlation_matrix = dataset.corr()
correlation_matrix

# Plotting the heatmap for correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.show()

"""# **MODELS**"""

models = {}
# Create an empty dictionary to store results for each model
results = {
    'Model': [],
    'Accuracy': [],
    'Precision': [],
    'Recall': [],
    'AUC': [],
    'FPR': [],
    'TPR': [],
    'ConfusionMatrix': []
}

lr_model = LogisticRegression(
    solver='lbfgs',
    C=1.0,
    max_iter=1000,
    random_state=0
)
lr_model.fit(X_train, y_train)
models['Logistic Regression'] = lr_model
print("Logistic Regression training complete.")

dt_model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=10,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=0
)
dt_model.fit(X_train, y_train)
models['Decision Tree'] = dt_model
print("Decision Tree training complete.")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

# Split training data into actual training + validation
X_train_nn, X_val_nn, y_train_nn, y_val_nn = train_test_split(
    X_train, y_train, test_size=0.1, random_state=0
)

# One-hot encode labels for multi-class classification
y_train_nn = to_categorical(y_train_nn, num_classes=3)  # Change 3 to the actual number of classes
y_val_nn = to_categorical(y_val_nn, num_classes=3)  # Change 3 to the actual number of classes

input_dimension_nn = X_train.shape[1]

# Define the model
nn_model = Sequential([
    InputLayer(input_shape=(input_dimension_nn,)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')  # Output layer with 3 units (one per class) and softmax activation
])

# Compile the model
nn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',  # Use categorical crossentropy for multi-class classification
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

# Print model summary
print("\nNeural Network Model Summary:")
nn_model.summary()

# Define early stopping callback
early_stopping_cb = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

# Train the model using validation data from the train set
print("\nStarting Neural Network training...")
history_nn = nn_model.fit(
    X_train_nn, y_train_nn,
    epochs=50,
    batch_size=32,
    validation_data=(X_val_nn, y_val_nn),
    callbacks=[early_stopping_cb],
    verbose=1
)

# Store the trained model
models['Neural Network'] = nn_model
print("Neural Network training complete.")

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    confusion_matrix, roc_auc_score, roc_curve
)
from sklearn.preprocessing import label_binarize
import numpy as np

# Get unique class labels and binarize y_test for multiclass ROC AUC
classes = np.unique(y_test)
n_classes = len(classes)
y_test_bin = label_binarize(y_test, classes=classes)

for name, model in models.items():
    print(f"\nEvaluating model: {name}")

    # Make predictions
    if name == 'Neural Network':
        y_proba = model.predict(X_test)
        y_pred = np.argmax(y_proba, axis=1)  # choose class with highest probability
    else:
        y_pred = model.predict(X_test)
        if hasattr(model, "predict_proba"):
            y_proba = model.predict_proba(X_test)
        else:
            y_proba = None

    # Store basic metrics
    results['Model'].append(name)
    results['Accuracy'].append(accuracy_score(y_test, y_pred))
    results['Precision'].append(precision_score(y_test, y_pred, average='macro', zero_division=0))
    results['Recall'].append(recall_score(y_test, y_pred, average='macro', zero_division=0))
    results['ConfusionMatrix'].append(confusion_matrix(y_test, y_pred))

    # Compute AUC and ROC
    if y_proba is not None and y_proba.shape[1] == n_classes:
        auc_score = roc_auc_score(y_test_bin, y_proba, average='macro', multi_class='ovr')
        fpr, tpr = {}, {}
        for i in range(n_classes):
            fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_proba[:, i])
    else:
        auc_score, fpr, tpr = None, None, None

    results['AUC'].append(auc_score)
    results['FPR'].append(fpr)
    results['TPR'].append(tpr)

print("\nAll models evaluated and metrics stored.")

"""Plot Accuracy, Precision, Recall"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plot a bar chart for each metric
metrics = ['Accuracy', 'Precision', 'Recall']
fig, axes = plt.subplots(1, 3, figsize=(18, 5))  # 1 row, 3 columns

for idx, metric in enumerate(metrics):
    sns.barplot(x=results['Model'], y=results[metric], ax=axes[idx])
    axes[idx].set_title(f'{metric} Comparison')
    axes[idx].set_ylim(0, 1)
    axes[idx].bar_label(axes[idx].containers[0], fmt='%.2f')

plt.tight_layout()
plt.show()

""" Plot Confusion Matrices"""

fig, axes = plt.subplots(1, len(models), figsize=(16, 5))
class_names=classes
if len(models) == 1:
    axes = [axes]  # Ensure list-like

for idx, cm in enumerate(results['ConfusionMatrix']):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[idx])
    axes[idx].set_title(f'{results["Model"][idx]} Confusion Matrix')
    axes[idx].set_xlabel('Predicted')
    axes[idx].set_ylabel('Actual')
    axes[idx].set_xticklabels(class_names)
    axes[idx].set_yticklabels(class_names)

plt.tight_layout()
plt.show()

""" Plot ROC Curve for Each Class in Each Model"""

from sklearn.metrics import auc

plt.figure(figsize=(10, 6))

for i in range(len(results['Model'])):
    fpr_dict = results['FPR'][i]
    tpr_dict = results['TPR'][i]

    if fpr_dict is not None:
        for j in range(len(classes)):
            fpr = fpr_dict[j]
            tpr = tpr_dict[j]
            auc_score = auc(fpr, tpr)
            label = f"{results['Model'][i]} (Class {class_names[j]}) - AUC: {auc_score:.3f}"
            plt.plot(fpr, tpr, label=label)

# Random baseline
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison (Multiclass)')
plt.legend(loc='lower right', fontsize='small')  # Smaller font if many labels
plt.grid()
plt.tight_layout()
plt.show()

"""Plot AUC"""

plt.figure(figsize=(10, 6))
sns.barplot(x=results['Model'], y=results['AUC'])
plt.title('Model AUC Score Comparison')
plt.ylabel('AUC Score')
plt.ylim(0, 1)
for index, auc_value_iter in enumerate(results['AUC']):
    plt.text(index, auc_value_iter + 0.01, f"{auc_value_iter:.4f}", ha='center')
plt.tight_layout()
plt.show()
print("AUC Score bar chart displayed.")

"""Summary Table of Metrics"""

import pandas as pd

results_df = pd.DataFrame({
    'Model': results['Model'],
    'Accuracy': results['Accuracy'],
    'Precision': results['Precision'],
    'Recall': results['Recall'],
    'AUC': results['AUC']
})

# Show nicely rounded results
display(results_df.round(3))

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    confusion_matrix, roc_auc_score, roc_curve
)
from sklearn.preprocessing import label_binarize

# Train Naive Bayes Model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
models['Naive Bayes'] = nb_model
print("Naive Bayes training complete.")

# Ensure test labels are binarized for multiclass AUC
classes = np.unique(y_test)
n_classes = len(classes)
y_test_bin = label_binarize(y_test, classes=classes)

# Evaluate the Naive Bayes model
print(f"\nEvaluating model: Naive Bayes")
y_pred = nb_model.predict(X_test)
y_proba = nb_model.predict_proba(X_test)

# Store metrics
results['Model'].append('Naive Bayes')
results['Accuracy'].append(accuracy_score(y_test, y_pred))
results['Precision'].append(precision_score(y_test, y_pred, average='macro', zero_division=0))
results['Recall'].append(recall_score(y_test, y_pred, average='macro', zero_division=0))
results['ConfusionMatrix'].append(confusion_matrix(y_test, y_pred))

# AUC and ROC
auc_score = roc_auc_score(y_test_bin, y_proba, average='macro', multi_class='ovr')
fpr, tpr = {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_proba[:, i])

results['AUC'].append(auc_score)
results['FPR'].append(fpr)
results['TPR'].append(tpr)

print("Naive Bayes evaluation complete.")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}, AUC: {auc_score:.4f}")